# Generated by Django 3.1.2 on 2020-11-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201127_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='post',
        ),
    ]
